package com.login;

import java.awt.Color;

public class Login extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

  
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JPanel();
        ExitTxt = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JLabel();
        Documento = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        InUsuario = new javax.swing.JTextField();
        InDocumento = new javax.swing.JTextField();
        Separador1 = new javax.swing.JSeparator();
        Separador2 = new javax.swing.JSeparator();
        Button = new javax.swing.JPanel();
        Entrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(58, 128, 177));
        Panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel1MouseDragged(evt);
            }
        });
        Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel1MousePressed(evt);
            }
        });

        ExitBtn.setBackground(new java.awt.Color(58, 128, 177));

        ExitTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExitTxt.setForeground(new java.awt.Color(255, 255, 255));
        ExitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitTxt.setText("X");
        ExitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitBtnLayout = new javax.swing.GroupLayout(ExitBtn);
        ExitBtn.setLayout(ExitBtnLayout);
        ExitBtnLayout.setHorizontalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        ExitBtnLayout.setVerticalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(0, 830, Short.MAX_VALUE)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 30));

        Panel2.setBackground(new java.awt.Color(58, 128, 177));

        jLabel1.setText("© Coltech 4.0 / 2025 / All rights Reserved");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel1)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Background.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 860, 30));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Logo.png"))); // NOI18N
        Background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        IniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        IniciarSesion.setForeground(new java.awt.Color(2, 155, 215));
        IniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesion.setText("INICIAR SESIÓN");
        Background.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 140, 30));

        Documento.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Documento.setText("DOCUMENTO");
        Background.add(Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 100, -1));

        Usuario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Usuario.setText("USUARIO");
        Background.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 90, -1));

        InUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InUsuario.setForeground(new java.awt.Color(204, 204, 204));
        InUsuario.setText("Ingrese su nombre de usuario");
        InUsuario.setBorder(null);
        InUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InUsuarioMousePressed(evt);
            }
        });
        InUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InUsuarioActionPerformed(evt);
            }
        });
        Background.add(InUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 180, 30));

        InDocumento.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InDocumento.setForeground(new java.awt.Color(204, 204, 204));
        InDocumento.setText("Ingrese su documento");
        InDocumento.setBorder(null);
        InDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InDocumentoMousePressed(evt);
            }
        });
        InDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InDocumentoActionPerformed(evt);
            }
        });
        Background.add(InDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 180, 30));

        Separador1.setBackground(new java.awt.Color(0, 0, 0));
        Separador1.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 160, 30));

        Separador2.setBackground(new java.awt.Color(0, 0, 0));
        Separador2.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(Separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 160, 30));

        Button.setBackground(new java.awt.Color(2, 155, 215));

        Entrar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Entrar.setText("ENTRAR");
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ButtonLayout = new javax.swing.GroupLayout(Button);
        Button.setLayout(ButtonLayout);
        ButtonLayout.setHorizontalGroup(
            ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        ButtonLayout.setVerticalGroup(
            ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Background.add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InDocumentoActionPerformed
      
    }//GEN-LAST:event_InDocumentoActionPerformed

    private void Panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Panel1MousePressed

    private void Panel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Panel1MouseDragged

    private void ExitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitTxtMouseClicked

    private void ExitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxtMouseEntered
        ExitBtn.setBackground(new Color(70,155,214));
        ExitTxt.setForeground(Color.red);
    }//GEN-LAST:event_ExitTxtMouseEntered

    private void ExitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTxtMouseExited
        ExitBtn.setBackground(new Color(58,128,177));
        ExitTxt.setForeground(Color.white);
    }//GEN-LAST:event_ExitTxtMouseExited

    private void EntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseEntered
        Button.setBackground(new Color(1,97,135));
    }//GEN-LAST:event_EntrarMouseEntered

    private void EntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseExited
        Button.setBackground(new Color(2,155,215));
    }//GEN-LAST:event_EntrarMouseExited

    private void InDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InDocumentoMousePressed
        if (InDocumento.getText().equals("Ingrese su documento")) {
            InDocumento.setText("");
            InDocumento.setForeground(Color.black);
        }
        if (String.valueOf(InUsuario.getText()).isEmpty()) {
            InUsuario.setText("Ingrese su nombre de usuario");
            InUsuario.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_InDocumentoMousePressed

    private void InUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InUsuarioActionPerformed

    private void InUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InUsuarioMousePressed
        if (String.valueOf(InDocumento.getText()).isEmpty()) {
            InDocumento.setText("Ingrese su documento");
            InDocumento.setForeground(new Color(204,204,204));
        }
        if (InUsuario.getText().equals("Ingrese su nombre de usuario")) {
        InUsuario.setText("");
        InUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_InUsuarioMousePressed

    private void EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Ingreso de login con los datos:\nDocumento: " + InDocumento.getText() + "\nUsuario: " + InUsuario.getText(), "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_EntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Button;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel Entrar;
    private javax.swing.JPanel ExitBtn;
    private javax.swing.JLabel ExitTxt;
    private javax.swing.JTextField InDocumento;
    private javax.swing.JTextField InUsuario;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
