package com.login;

import java.awt.Color;

public class Login extends javax.swing.JFrame {
    
    
    int xMouse, yMouse;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        PanelExit = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        IngreseUsuario = new javax.swing.JTextField();
        Separador1 = new javax.swing.JSeparator();
        Contrasena = new javax.swing.JLabel();
        Separador2 = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();
        Bottom = new javax.swing.JPanel();
        Entrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(58, 128, 177));
        Panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel1MouseDragged(evt);
            }
        });
        Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel1MousePressed(evt);
            }
        });

        PanelExit.setBackground(new java.awt.Color(58, 128, 177));

        exitTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelExitLayout = new javax.swing.GroupLayout(PanelExit);
        PanelExit.setLayout(PanelExitLayout);
        PanelExitLayout.setHorizontalGroup(
            PanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );
        PanelExitLayout.setVerticalGroup(
            PanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(0, 761, Short.MAX_VALUE)
                .addComponent(PanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        Panel2.setBackground(new java.awt.Color(58, 128, 177));

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Background.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 800, 40));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/icon.png"))); // NOI18N
        Background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 380, 80));

        IniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        IniciarSesion.setForeground(new java.awt.Color(2, 155, 215));
        IniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesion.setText("INCIAR SESIÓN");
        Background.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 150, 30));

        Usuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Usuario.setText("USUARIO");
        Background.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 70, -1));

        IngreseUsuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        IngreseUsuario.setForeground(new java.awt.Color(204, 204, 204));
        IngreseUsuario.setText("Ingrese su nombre de usuario");
        IngreseUsuario.setBorder(null);
        IngreseUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngreseUsuarioMousePressed(evt);
            }
        });
        Background.add(IngreseUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 210, -1));

        Separador1.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 190, 10));

        Contrasena.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Contrasena.setText("CONTRASEÑA");
        Background.add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 110, -1));

        Separador2.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(Separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 190, 10));

        Password.setForeground(new java.awt.Color(204, 204, 204));
        Password.setText("********");
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        Background.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 190, 30));

        Bottom.setBackground(new java.awt.Color(2, 155, 215));

        Entrar.setBackground(new java.awt.Color(255, 255, 255));
        Entrar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Entrar.setText("ENTRAR");
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BottomLayout = new javax.swing.GroupLayout(Bottom);
        Bottom.setLayout(BottomLayout);
        BottomLayout.setHorizontalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        BottomLayout.setVerticalGroup(
            BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(Bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MousePressed
     xMouse = evt.getX();
     yMouse = evt.getY();
    }//GEN-LAST:event_Panel1MousePressed

    private void Panel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Panel1MouseDragged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        PanelExit.setBackground(new Color (45,100,138));
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        PanelExit.setBackground(new Color (58,128,177));
    }//GEN-LAST:event_exitTxtMouseExited

    private void EntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseEntered
        Bottom.setBackground(new Color (2,180,250));
    }//GEN-LAST:event_EntrarMouseEntered

    private void EntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseExited
        Bottom.setBackground(new Color (2,155,215));
    }//GEN-LAST:event_EntrarMouseExited

    private void IngreseUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngreseUsuarioMousePressed
        IngreseUsuario.setText("");
        IngreseUsuario.setForeground(Color.black);
        Password.setText("********");
        Password.setForeground(Color.gray);
    }//GEN-LAST:event_IngreseUsuarioMousePressed

    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed
        IngreseUsuario.setText("Ingrese su nombre de usuario");
        IngreseUsuario.setForeground(Color.gray);
        Password.setText("");
        Password.setForeground(Color.black);
    }//GEN-LAST:event_PasswordMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Bottom;
    private javax.swing.JLabel Contrasena;
    private javax.swing.JLabel Entrar;
    private javax.swing.JTextField IngreseUsuario;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel PanelExit;
    private javax.swing.JPasswordField Password;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel exitTxt;
    // End of variables declaration//GEN-END:variables
}
